name: "Primary Build" # Name of the workflow

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  pull_request: # Triggers the workflow on pull requests to the main branch
    branches: [ main ]
  push: # Triggers the workflow on pushes to the main branch and tags starting with 'v'
    branches: [ main ]
    tags: [ v* ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub token for authentication

jobs:
  test:
    name: Execute Tests (${{ matrix.os }}, Java ${{ matrix.java }}) # Job name with dynamic OS and Java version
    strategy:
      fail-fast: false # Continue running all jobs even if one fails
      matrix:
        java: [ 17, 21, 23 ] # Java versions to test
        os: [ ubuntu-24.04, windows-2025 ] # Operating systems to test
    runs-on: ${{ matrix.os }} # Run the job on the specified OS

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4 # Checkout the source code from the repository
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Setup Java
        uses: actions/setup-java@v4 # Set up the specified Java version
        with:
          distribution: "temurin" # Use the Temurin distribution of Java
          java-version: ${{ matrix.java }} # Use the Java version from the matrix
          check-latest: true # Check for the latest version of the specified Java version

      - name: Setup SBT
        uses: sbt/setup-sbt@v1 # Set up SBT (Simple Build Tool)

      - name: Compile 'chromisery-pos' Module
        run: sbt chromisery-pos/compile # Run the SBT package command to build the project

      # TODO: Add unit testing tasks